name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Install dependencies
        run: pip install pytest
      - name: tests unitaires - codebinaire
        run:
          pytest ./tests/test_codebinaire.py
      - name: tests unitaires - demo_lecteur
        run:
          pytest ./tests/demo_lecteur.py
